work_dir_name = "project"
work_dir = f"/home/{work_dir_name}"
modifications_tag_name = "bolt_file_modifications"

allowed_HTML_elements = """
    '<a>',
    '<b>',
    '<blockquote>',
    '<br>',
    '<code>',
    '<dd>',
    '<del>',
    '<details>',
    '<div>',
    '<dl>',
    '<dt>',
    '<em>',
    '<h1>',
    '<h2>',
    '<h3>',
    '<h4>',
    '<h5>',
    '<h6>',
    '<hr>',
    '<i>',
    '<ins>',
    '<kbd>',
    '<li>',
    '<ol>',
    '<p>',
    '<pre>',
    '<q>',
    '<rp>',
    '<rt>',
    '<ruby>',
    '<s>',
    '<samp>',
    '<source>',
    '<span>',
    '<strike>',
    '<strong>',
    '<sub>',
    '<summary>',
    '<sup>',
    '<table>',
    '<tbody>',
    '<td>',
    '<tfoot>',
    '<th>',
    '<thead>',
    '<tr>',
    '<ul>',
    '<var>',
  """